/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary": "#006a48",
        "on-primary-container": "#fffdff",
        "inverse-primary": "#b0c6ff",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#dce3eb",
        "primary-container": "#1b6ef3",
        "primary-fixed": "#d9e2ff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#001945",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed-variant": "#00419c",
        "outline-variant": "#c2c6d7",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d3e4fe",
        "primary": "#0056c9",
        "on-primary": "#ffffff",
        "tertiary-container": "#00865c",
        "surface": "#f8f9ff",
        "on-secondary-container": "#5e656c",
        "surface-container-high": "#dce9ff",
        "surface-tint": "#0057cc",
        "inverse-surface": "#213145",
        "on-surface-variant": "#424654",
        "on-secondary-fixed-variant": "#40484e",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b0c6ff",
        "secondary-fixed-dim": "#c0c7cf",
        "outline": "#727786",
        "on-secondary-fixed": "#151c22",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#fafff9",
        "surface-variant": "#d3e4fe",
        "secondary": "#585f66",
        "secondary-fixed": "#dce3eb",
        "on-background": "#0b1c30"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "gutter": "24px",
        "sm": "12px",
        "md": "24px",
        "xs": "4px",
        "margin-mobile": "16px",
        "lg": "40px",
        "container-max": "1200px",
        "xl": "64px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
